name: root
channels:
  - conda-forge
  - pytorch
dependencies:
  - flake8
  - scipy
  - numpy
  - pandas
  - jupyter
  - matplotlib
  - scikit-learn
  - scikit-image
  - pytorch-cpu
  - torchvision-cpu
  - pip:
    - https://api.github.com/repos/paris-saclay-cds/ramp-workflow/zipball/master
